### PR TITLE
1176 remove `Show Warnings` from modules

### PR DESCRIPTION
**Pull request by m7pr**
Part of https://github.com/insightsengineering/teal/issues/1176

### CODE REVIEW

**Comment by m7pr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kartikeyakirar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by kartikeyakirar — APPROVED** [review]
LGTM!! no more occurrence of teal.code::get_warnings(). Could you please add a news entry for this?

Note: @m7pr I have added end line to fix CI issues[b30aa5b](https://github.com/insightsengineering/teal.osprey/pull/264/commits/b30aa5b357c26e665117be0de0d9d68e9cbcf4e6)

**Comment by m7pr** [comment]
Yup, thanks

**Pull request merged**
