### PR TITLE
Fix pkgdown redirect

### PR DESCRIPTION
**Pull request by vedhav**
Part of https://github.com/insightsengineering/coredev-tasks/issues/506

### CODE REVIEW

**Review by m7pr — COMMENTED** [review]
@vedhav you sure you wanted to update so many .Rd files?

**Comment by vedhav** [comment]
Let me check this. This is weird. There is no change to roxygen2 version here so there should not be this many .Rd changes.

**Comment by m7pr** [comment]
It's a change reflecting the `@rdname` tag change (from `?teal::module` into `?teal::_teal_module`) from here https://github.com/insightsengineering/teal/issues/1074 done in here https://github.com/insightsengineering/teal/pull/1087

**Comment by vedhav** [comment]
Got it, Then it looks alright to me. There was just a warning from using the older `@docType package` syntax so I updated it.

**Review by m7pr — APPROVED** [review]

**Pull request merged**
