### PR TITLE
140 teal.reporter@main

### PR DESCRIPTION
**Pull request by denisovan31415**
closes https://github.com/insightsengineering/teal.osprey/issues/140

### CODE REVIEW

**Comment by nikolas-burkoff** [comment]
You'll need to add teal.reporter to the staged.dependencies yaml file (and open a PR in teal.reporter with the same branch name with teal.osprey as a downstream dependency in its staged.deps yaml file

**Review by nikolas-burkoff — COMMENTED** [review]
@junlueZH I think this is almost ready to go (I pushed a few minor changes to make osprey consistent with goshawk)

- Do you know if you can get the dimensions of the plots out for modules which use `tm_g_decorate` (`tm_g_events_term_id` and others)?
- @kumamiao what do you mean by 
image

@kumamiao - apart from the above I think this is good to go - feel free to also review and we'll merge by the end of the week

**Review by nikolas-burkoff — APPROVED** [review]
We'll wait for Nina to approve but from my perspective I'm happy

**Comment by kumamiao** [comment]
> @kumamiao what do you mean by
image

Sorry I meant that the preset filters on the top left of encoding will be needed in the reporter. This long sentence is the description from the encoding panel. :)
Screen Shot 2022-07-13 at 9 05 25 AM

**Comment by junlueZH** [comment]
@kumamiao I have added the Preset Filters to the Butterfly plot. This PR is ready for review.

**Comment by kumamiao** [comment]
Yes looks good, please merge @nikolas-burkoff , thank you!

**Pull request merged**
